---
checks:
  file-lines:
    enabled: false
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- .idea/
- docs/
- dist/
- node_modules/
- lib/
- es/
- test/
- webpack.config.cjs
- webpack.config-test.web.cjs
- jsdoc.cjs
